import path from 'node:path';
import { mkdir, readFile, readdir, writeFile } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { afterAll, beforeAll, describe, expect, it } from 'vitest';
import { openDatabase } from '../src/db/database.js';
import { buildFixtureRepo } from '../src/demo/fixture-repo.js';
import { inspectProject } from '../src/project/inspect.js';
import { parseReviewProfile } from '../src/review/profiles.js';
import { sha256 } from '../src/shared/hash.js';
import { silentLogger } from '../src/shared/logger.js';
import { datasetSchema, snapshotFromDataset } from '../src/workflow/research.js';
import { migrateWorkspace, type MigrationReport } from '../src/workflow/migrate.js';
import { clock, FIXTURES, fixturePublications, tempDir } from './helpers.js';

const V1_PRESET = `schemaVersion: 1
id: my-diary
version: 1.0.0
displayName: My diary
description: Personal development diary.
perspective: first-person
narrativeMode: chronological
technicalDepth: moderate
contextDepth: moderate
pacing: brisk
openingBehavior: Start with what happened this week.
sectionBehavior: Sections follow days.
codeUsage: sparing
visualUsage: sparing
humorLevel: light
personalPresence: high
failureDiscussion: honest
limitationsBehavior: Mention what is still broken.
preferredPatterns: [One episode per section.]
avoidPatterns: [Release-notes tone., Section titles copied from story.json fields.]
suitablePublicationTypes: [short-project-update]
notes: []
`;

/** A v2 (editorial-kit) workspace with every kind of legacy data. */
async function legacyWorkspace(root: string): Promise<Record<string, string>> {
  const repo = path.join(root, 'notegarden');
  await buildFixtureRepo(path.join(FIXTURES, 'projects/notegarden/history.json'), repo);
  const config = { schemaVersion: 1, language: 'ru', author: { name: 'Demo Author', profiles: {} }, projects: [{ id: 'notegarden', name: 'Notegarden', path: './notegarden', glossary: [{ term: 'аудит', aliases: ['audit'] }] }], editorial: { defaultStyle: 'engineering-story' }, screenshots: { outputDir: 'images' }, paths: { editorialDir: '.editorial', articlesDir: 'articles' } };
  const files: Record<string, string> = {};
  const put = async (rel: string, content: string) => {
    await mkdir(path.dirname(path.join(root, rel)), { recursive: true });
    await writeFile(path.join(root, rel), content);
    files[rel] = sha256(content);
  };
  await put('editorial.config.json', JSON.stringify(config, null, 2));
  for (const p of await fixturePublications()) await put(`.editorial/publications/${p.platform}/${p.id.split(':')[1]}.json`, JSON.stringify(p));
  const dataset = datasetSchema.parse(JSON.parse(await readFile(path.join(FIXTURES, 'platform/habr-weekly-2026-09-17.json'), 'utf8')));
  await put('.editorial/research/2026-09-17/habr.json', JSON.stringify(snapshotFromDataset(dataset)));
  const report = await inspectProject({ projectId: 'notegarden', name: 'Notegarden', root: repo, clock, logger: silentLogger });
  await put('.editorial/projects/notegarden/report.json', JSON.stringify(report));
  await put('.editorial/styles/my-diary.yaml', V1_PRESET);
  await put('.editorial/author-profile.json', JSON.stringify({ schemaVersion: 1, manual: { tone: 'спокойный' } }));
  await put('articles/old-story/story.json', '{"slug":"old-story"}');
  await put('articles/old-story/outputs/habr.md', '# Old generated draft\n\nThis was generated by v2.\n');
  return files;
}

describe('storyops migrate (v2 → v3 workspace)', () => {
  let root: string;
  let cleanup: () => Promise<void>;
  let before: Record<string, string>;
  let report: MigrationReport;

  beforeAll(async () => {
    const tmp = await tempDir('storyops-migrate-');
    root = tmp.dir;
    cleanup = tmp.cleanup;
    before = await legacyWorkspace(root);
    report = await migrateWorkspace(root, { clock, logger: silentLogger });
  }, 60_000);
  afterAll(async () => cleanup?.());

  it('a dry run creates nothing', async () => {
    const tmp = await tempDir();
    try {
      await legacyWorkspace(tmp.dir);
      const listing = (await readdir(tmp.dir)).sort();
      const dry = await migrateWorkspace(tmp.dir, { dryRun: true, clock, logger: silentLogger });
      expect(dry.dryRun).toBe(true);
      expect(dry.publications.found).toBe(3);
      expect(dry.config.created).toBe(true);
      expect((await readdir(tmp.dir)).sort()).toEqual(listing);
    } finally {
      await tmp.cleanup();
    }
  }, 60_000);

  it('writes storyops.config.json without generation-only fields', async () => {
    const cfg = JSON.parse(await readFile(path.join(root, 'storyops.config.json'), 'utf8'));
    expect(cfg.schemaVersion).toBe(2);
    expect(cfg.editorial).toBeUndefined();
    expect(cfg.paths.articlesDir).toBeUndefined();
    expect(cfg.screenshots).toBeUndefined();
    expect(cfg.review.profile).toBe('engineering-story');
    expect(report.config.removedFields).toEqual(['editorial', 'screenshots', 'paths.articlesDir']);
  });

  it('preserves author history, Habr snapshots and repository reports in the database', async () => {
    expect(report.publications).toMatchObject({ found: 3, added: 3 });
    expect(report.snapshots).toEqual([expect.objectContaining({ file: path.join('.editorial', 'research', '2026-09-17', 'habr.json'), runId: 1, duplicate: false })]);
    expect(report.repositories[0]).toMatchObject({ id: 'notegarden' });
    expect(report.repositories[0]!.events).toBeGreaterThan(5);
    const { db } = await openDatabase(path.join(root, '.storyops', 'storyops.db'), { readOnly: true });
    expect(db.value('SELECT COUNT(*) FROM author_publications')).toBe(3);
    expect(db.value("SELECT origin FROM research_runs WHERE id = 1")).toBe('legacy-snapshot');
    expect(db.value('SELECT COUNT(*) FROM platform_articles')).toBe(20);
    expect(db.value('SELECT COUNT(*) FROM trend_snapshots')).toBeGreaterThan(0);
    expect(db.value("SELECT COUNT(*) FROM repository_events WHERE repository_id = 'notegarden'")).toBe(report.repositories[0]!.events);
    db.close();
  });

  it('converts workspace style presets into review profiles and keeps the author profile', async () => {
    expect(report.reviewProfiles).toEqual([{ from: path.join('.editorial', 'styles', 'my-diary.yaml'), to: path.join('.storyops', 'review-profiles', 'my-diary.yaml') }]);
    const file = path.join(root, '.storyops', 'review-profiles', 'my-diary.yaml');
    const parsed = parseReviewProfile(await readFile(file, 'utf8'), file);
    expect(parsed.issues).toEqual([]);
    expect(parsed.profile!.expectations).toMatchObject({ firstPerson: 'expected', flow: 'chronological', codeRole: 'sparing', limitations: 'expected' });
    expect(parsed.profile!.watchFor).toEqual(['Release-notes tone.']);
    expect(report.authorProfile).toBe('copied');
    expect(JSON.parse(await readFile(path.join(root, '.storyops', 'author', 'author-profile.json'), 'utf8')).manual.tone).toBe('спокойный');
  });

  it('never deletes or modifies user files; old drafts are kept and not imported as publications', async () => {
    for (const [rel, hash] of Object.entries(before)) expect(sha256(await readFile(path.join(root, rel), 'utf8')), rel).toBe(hash);
    expect(report.notImported).toEqual([expect.stringMatching(/^articles\/old-story\/outputs\/habr\.md \(v2 draft; user file, kept, not treated as a publication\)$/)]);
    expect(report.untouched).toEqual(expect.arrayContaining(['editorial.config.json', '.editorial', 'articles/']));
    expect(existsSync(path.join(root, '.storyops', 'migration-report.md'))).toBe(true);
  });

  it('is idempotent', async () => {
    const again = await migrateWorkspace(root, { clock, logger: silentLogger });
    expect(again.config.created).toBe(false);
    expect(again.publications).toMatchObject({ found: 3, added: 0, unchanged: 3 });
    expect(again.snapshots[0]).toMatchObject({ runId: 1, duplicate: true });
    expect(again.reviewProfiles[0]!.skipped).toMatch(/already exists/);
    const { db } = await openDatabase(path.join(root, '.storyops', 'storyops.db'), { readOnly: true });
    expect(db.value('SELECT COUNT(*) FROM research_runs')).toBe(1);
    db.close();
  });
});
